config/routes.rb
Rails.application.routes.draw do
  get 'example/show'

  resources :photos
  get 'welcome/index'

  resources :stores

  root 'welcome#index'

  devise_for :users, :controllers => { registrations:
  'registrations' }

    resources :stores do
      resources :comments
    end

resource :example, only: [:show], controller: :example
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :store

  validates :content, presence: true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :download,
                    :storage => :s3,
                    :s3_credentials => Proc.new{|a| a.instance.s3_credentials }

                    validates_attachment_content_type :download, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def s3_credentials
    {:bucket => "popstar", :aws_access_key_id => ENV["AWS_ACCESS_KEY_ID"], :aws_secret_access_key => ENV["AWS_SECRET_ACCESS_KEY"]}
  end
end

app/models/store.rb
class Store < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :user_id, :image, :zipcode, :long_description,  presence: true

  searchable do
    text :caption, :zipcode, :long_description
    end


has_attached_file :image, styles: { :medium => "640x" }
validates_attachment_content_type :image, :content_type =>
/\Aimage\/.*\Z/

has_attached_file :image2, styles: { :medium => "640x" }
validates_attachment_content_type :image2, :content_type =>
/\Aimage\/.*\Z/

has_attached_file :image3, styles: { :medium => "640x" }
validates_attachment_content_type :image3, :content_type =>
/\Aimage\/.*\Z/

has_attached_file :image4, styles: { :medium => "640x" }
validates_attachment_content_type :image4, :content_type =>
/\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :stores, dependent: :destroy
  validates :company_name, presence: true
  has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base



  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # Thanks to Ben Walker at Dev walks for the Instagram template on which this #site's foundation is based : https://www.devwalks.com/.
  
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_store

  def create

    @comment = @store.comments.build(comment_params)
    @comment.user_id = current_user.id
      if @comment.save

        redirect_to :back

    else

        render root_path
    end
  end

  def show
   @store = Store.find(params[:id])
   @comment = Comment.new(store: @store)

  end

  def destroy
    @comment = @store.comments.find(params[:id])
    @comment.destroy
    redirect_to :back
  end

private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_store
  @store = Store.find(params[:store_id])
end


end

app/controllers/example_controller.rb
class ExampleController < ApplicationController
  def show
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Your image was successfully uploaded.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:attachment, :description, :download)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def search
    if params[:search]
               search_param = CGI::escapeHTML(params[:search])

               redirect_to ("/stores?search=#{search_param}&commit=Search")

              return
         end
  end

  private

  def sign_up_params
    params.require(:user).permit(:company_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:company_name, :email, :password, :password_confirmation)
  end



end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :authenticate_user!
  before_action :owned_store, only: [:edit, :update, :destroy]

  def index

    @search = Store.search do
      fulltext params[:search]
    end
    @stores = @search.results

  end

  def new
    @store = current_user.stores.build
  end

  def create
    @store = current_user.stores.build(store_params)
    if @store.save
      redirect_to store_path(@store)
    else
      render :new
    end
  end

  def show
    @store = Store.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @store = Store.find(params[:id])
  end

  def update
    @store = Store.find(params[:id])
    @store.update(store_params)
    redirect_to(store_path(@store))
  end

  def destroy
    @store = Store.find(params[:id])
    @store.destroy
    redirect_to stores_path

  end

  private

  def store_params
    params.require(:store).permit(:image, :image2, :image3, :image4, :caption, :zipcode, :long_description)
  end

  def set_store
    @store = Store.find(params[:id])
  end

  def owned_store
    @store = Store.find(params[:id])
    unless current_user == @store.user
      redirect_to root_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if params[:search]
             search_param = CGI::escapeHTML(params[:search])

             redirect_to ("/stores?search=#{search_param}&commit=Search")

            return
       end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/example_helper.rb
module ExampleHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/example/show.html.erb
<h1>Example#show</h1>
<p>Find me in app/views/example/show.html.erb</p>





<button class="fuck">fuck you</button>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">

    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <ul class="nav navbar-nav navbar-left">
    <li><%= link_to image_tag("popstar_logo.png", :size => "80x80"), root_path %></li>
  </ul>
  </div>
  <form class="navbar-form navbar-left search-bar" role="search">

  <div class="form-group">

  <%= form_tag stores_path, :method => :get do %>
      <%= text_field_tag :search, params[:search], :placeholder => "Search"  %>
      <%= submit_tag "Find My Space", :class => "btn btn-default",  :name => nil, :class => 'polina_button frontpage' %>
  <% end %>

</div>
</form>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>

      <li><%= link_to "Open Popup", new_store_path %></li>
      <li><%= link_to "Find Popups", stores_path %></li>
      <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>

      <% else %>

      <li><%= link_to "Login", new_user_session_path %></li>
      <li><%= link_to "Register", new_user_registration_path %></li>
      <% end %>

    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

app/views/layouts/_normalnav.html.erb
<nav class="navbar navbar-default nav_main_opacity normalnav">
<div class="container-fluid fluid_border">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">

    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <ul class="nav navbar-nav navbar-left">
    <li><%= link_to image_tag("popstar_logo.png", class: "logo", :size => "80x80"), root_path %></li>
  </ul>
  </div>
  <form class="navbar-form navbar-left search-bar" role="search">

  <div class="form-group">

  <%= form_tag stores_path, :method => :get do %>
      <%= text_field_tag :search, params[:search], :placeholder => "Search"  %>
      <%= submit_tag "Find My Space", :class => "btn btn-default",  :name => nil, :class => 'polina_button frontpage' %>
  <% end %>

</div>
</form>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>

      <li><%= link_to "Open Popup", new_store_path %></li>
      <li><%= link_to "Find Popups", stores_path %></li>
      <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>

      <% else %>

      <li><%= link_to "Login", new_user_session_path %></li>
      <li><%= link_to "Register", new_user_registration_path %></li>
      <% end %>

    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Popstar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<link href='https://fonts.googleapis.com/css?family=Dosis|Hind|Maven+Pro|Gudea:400,400italic,700' rel='stylesheet' type='text/css'>

<link rel="icon"
      type="image/png"
      href="https://s3.amazonaws.com/popstarimages/popstarfavicon.png">

</head>
<body>
  <div class="main_container">
    <% if current_page?(root_path) %>
        <%= render 'layouts/navbar' %>
        <% elsif current_page?(new_user_registration_path)  %>
        <%= render 'layouts/navbar' %>
        <% elsif current_page?(new_user_session_path)  %>
        <%= render 'layouts/navbar' %>

        <% else %>
        <%= render 'layouts/normalnav' %>
    <% end %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>

</div>
</body>
</html>

app/views/mobile_views/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Mobile Popstar</title>
  </head>
  <body>

  </body>
</html>

app/views/photos/_form.html.erb
<%= simple_form_for(@photo) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.file_field :photo, placeholder: "Upload Photo"%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Photos</h1>

<table>
  <thead>
    <tr>
      <th>Attachment</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.attachment %></td>
        <td><%= photo.description %></td>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Attachment:</strong>
  <%= @photo.attachment %>
  <%= image_tag current_user.photo %>
</p>

<p>
  <strong>Description:</strong>
  <%= @photo.description %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>

app/views/stores/_store.html.erb
<div id="comment">

  <div class="user-name">
    <%= comment.user.company_name %>
  </div>

  <div class="comment-content">
    <%= comment.content %>
  </div>

  <!-- If comment belongs to current user, user will have a X-shaped icon for deleting it -->
  <% if comment.user == current_user %>
    <!-- <remote: true> = let Rails know we want to delete our comment via AJAX -->
    <%= link_to store_comment_path(store, comment), method: :delete, data: { confirm: "Are you sure?" }, remote: true do %>
      <span class="glyphicon glyphicon-remove delete-comment"></span>
    <% end %>
  <% end %>

</div>

app/views/stores/edit.html.erb
<div class="backstop">

<div class="new_store_container">

  <h1 class="new_store_header">Edit Your Space</h1>


    <div class="add_store">
    <div class="add_form_field"><%= simple_form_for @store do |f| %></div>
    <div class="add_form_field"><%= f.input :image %></div><hr>
    <div class="add_form_field"><%= f.input :image2 %></div><hr>
    <div class="add_form_field"><%= f.input :image3 %></div><hr>
    <div class="add_form_field"><%= f.input :image4 %></div><hr>

    <div class="add_form_field"><%= f.input :zipcode, :placeholder => 'Property Zipcode', label: false %></div><hr>
    <div class="add_form_field"><%= f.input :caption, :id => "headline", :placeholder => 'Headline', label: false%></div><hr>
    <div class="add_form_field"><h6>Please describe your property</h6></div>
    <div class="add_form_field"><%= f.text_area :long_description, :id => "message_area", :cols => 50, :rows => 10 %></div>

    <%= f.button :submit %>
    <% end %>
    </div>
</div>

app/views/stores/index.html.erb
<div class="outer">
<div class="mini_container">
<% @stores.each do |store| %> <div class="index_div">
  <div class="crop"><%= link_to image_tag(store.image.url(:medium),width: '100%', height: '100%', alt: 'Real Estate Image', class: "img-responsive"), store_path(store) %>  <h3 class="inside_text"> <span class="inside_span"> <%= store.caption %></span> </h3>
</div>
</div>
<div>

<% end %>
</div>

app/views/stores/new.html.erb
<div class="backstop">

<div class="new_store_container">

  <h1 class="new_store_header">List Your Space</h1>


    <div class="add_store">
    <div class="add_form_field"><%= simple_form_for @store do |f| %></div>
    <div class="add_form_field"><%= f.input :image %></div><hr>
    <div class="add_form_field"><%= f.input :image2 %></div><hr>
    <div class="add_form_field"><%= f.input :image3 %></div><hr>
    <div class="add_form_field"><%= f.input :image4 %></div><hr>

    <div class="add_form_field"><%= f.input :zipcode, :placeholder => 'Property Zipcode', label: false %></div><hr>
    <div class="add_form_field"><%= f.input :caption, :id => "headline", :placeholder => 'Headline', label: false%></div><hr>
    <div class="add_form_field"><h6>Please describe your property</h6></div>
    <div class="add_form_field"><%= f.text_area :long_description, :id => "message_area", :cols => 50, :rows => 10 %></div>

    <%= f.button :submit  %>
    <% end %>
    </div>
</div>

app/views/stores/old.html.erb
<div class="slider">
    <ul class="frames">
        <li id="one" class="slide">
          <%= image_tag(@store.image(:medium), class: "img-responsive") %>
            <nav>
                <a class="prev" href="#five">&larr;</a>
                <a class="next" href="#two">&rarr;</a>
            </nav>
        </li>
        <li id="two" class="slide">
          <%= image_tag(@store.image2(:medium), class: "img-responsive") %>
            <nav>
                <a class="prev" href="#one">&larr;</a>
                <a class="next" href="#three">&rarr;</a>
            </nav>
        </li>
        <li id="three" class="slide">
          <%= image_tag(@store.image3(:medium), class: "img-responsive") %>
            <nav>
                <a class="prev" href="#two">&larr;</a>
                <a class="next" href="#four">&rarr;</a>
            </nav>
        </li>
        <li id="four" class="slide">
          <%= image_tag(@store.image4(:medium), class: "img-responsive") %>
            <nav>
                <a class="prev" href="#three">&larr;</a>
                <a class="next" href="#five">&rarr;</a>
            </nav>
        </li>
        <li class="quicknav">
            <ul>
                <li><a href="#one"></a></li>
                <li><a href="#two"></a></li>
                <li><a href="#three"></a></li>
                <li><a href="#four"></a></li>
                <li><a href="#five"></a></li>
            </ul>
        </li>
    </ul>
</div>

<br>
<br>
<br>
<br>

<h2> Company Name: <%= @store.user.company_name %> </h2>
<h3> Headline: <%= @store.caption %> </h3>
<p> Zipcode: <%= @store.zipcode %> </p>
<p> Long Description: <%= @store.long_description %> </p>

<div class="lightbox">
<button class="back">Back</button>

<div class="picture-container">


</div>
<button class="forward">Forward</button>

</div>



<div class="picture pic1"><%= image_tag(@store.image(:medium), class: "img-responsive") %></div>
<div class="picture pic2"><%= image_tag(@store.image2(:medium), class: "img-responsive") %></div>
<div class="picture pic3"><%= image_tag(@store.image3(:medium), class: "img-responsive") %></div>
<div class="picture pic4"><%= image_tag(@store.image4(:medium), class: "img-responsive") %></div>





  <% if @store.user.id == current_user.id %>

  <button><%= link_to 'Edit Your Store', edit_store_path(@store) %></button>


  <button><%= link_to "Delete", store_path(@store), method: :delete, data: {confirm: "Are you sure you  want to delete this store?"}%></button>

  <% end %>

  <!-- Display Add Comment -->

    <div class="comment-form col-sm-11">
      <%= form_for [@store, @store.comments.new] do |f| %>
      <%= f.text_field :content, placeholder: 'Add'%>
      <%= f.submit 'Add'%>
    </div>
    <div>
        <% if @store.comments %>
          <% @store.comments.each do |comment| %>
        <!-- Display Actual Comment -->

         <div class="comment-content">
          <%= comment.content %>
          <% if comment.user == current_user %>
          <button><%= link_to "Delete This Comment",  store_comment_path(@store, comment), method: :delete, data: { confirm: "Are you sure?" } %></button>
          <% end %>
        </div>

    </div>
    <% end %>
    <% end %>

    <% end %>

app/views/stores/show.html.erb
  <!-- Top Image start -->
  <div class="slider">
      <ul class="frames">
          <li id="one" class="slide">
            <%= image_tag(@store.image(:medium), class: "img-responsive") %>
              <nav>
                  <a class="prev" href="#four">&larr;</a>
                  <a class="next" href="#two">&rarr;</a>
              </nav>
          </li>
          <li id="two" class="slide">
            <%= image_tag(@store.image2(:medium), class: "img-responsive") %>
              <nav>
                  <a class="prev" href="#one">&larr;</a>
                  <a class="next" href="#three">&rarr;</a>
              </nav>
          </li>
          <li id="three" class="slide">
            <%= image_tag(@store.image3(:medium), class: "img-responsive") %>
              <nav>
                  <a class="prev" href="#two">&larr;</a>
                  <a class="next" href="#four">&rarr;</a>
              </nav>
          </li>
          <li id="four" class="slide">
            <%= image_tag(@store.image4(:medium), class: "img-responsive") %>
              <nav>
                  <a class="prev" href="#three">&larr;</a>
                  <a class="next" href="#one">&rarr;</a>
              </nav>
          </li>
          <li class="quicknav">
              <ul>
                  <li><a href="#one"></a></li>
                  <li><a href="#two"></a></li>
                  <li><a href="#three"></a></li>
                  <li><a href="#four"></a></li>
              </ul>
          </li>
      </ul>
  </div>
  <!-- Top Image ends -->

<br>
<br>
<br>
<br>
<br>
<h2 class="store_caption"> <%= @store.caption %> </h2>
<hr>

  <!-- show company name & zipcode start -->
  <div>
    <div class= "contains_inners">
      <h5 class="details">Details</h5>
    </div>

    <br>
    <hr>
    <div class= "contains_inners">
      <div class="first_inner">Company Name:</div>
      <div class="long_descriptionn second_inner"><p> <%= @store.user.company_name %> </p></div>
    </div>


    <div class= "contains_inners">
      <div class="first_inner">Property Zipcode:</div>
      <div class="long_descriptionn second_inner"><%= @store.zipcode %> </p></div>
    </div>
  </div>
  <!-- show company name & zipcode ends -->

<br>
<hr>

  <!-- Long Description start -->
  <div class= "second_details">
    <div class= "contains_inners">
    </div>

    <div class= "contains_inners">
      <div class="first_inner">Description: </div>
      <div class="long_descriptionn second_inner"><p> <div class="long_descriptionn"><p><%= @store.long_description %> </p> </div>
   </p></div>
    </div>
  </div>
  <!-- Long Description ends -->

<br>
<hr>

  <!-- show edit / delete store start -->
  <% if @store.user.id == current_user.id %>

  <div class="edit_buttons">


    <div class="edit_buttons_themselves"><%= link_to 'Edit Your Store', edit_store_path(@store), {:class => "polina_buttonn", :style=>'text-align:center'}; %></div>


    <div class="edit_buttons_themselves"><%= link_to "Delete This Store", store_path(@store), method: :delete, data: {confirm: "Are you sure you  want to delete this store?"}, :class => "polina_buttonn" %></div>

  </div>
  <hr>

  <% end %>

  <!-- show edit / delete store ends -->

<br>
<br>

  <!-- Add Comment Form Start -->
  <div class="comments_section">
    <h2>Add A Comment</h2>
    <br>
      <div class="comment-form col-sm-11">
        <%= form_for [@store, @store.comments.new] do |f| %>
        <%= f.text_field :content, placeholder: 'Add a Comment'%>
        <%= f.submit 'Add a Comment', :class => "Add"%>
      </div>
    <br>
    <br>
    <br>
      <div class="comments_if">
        <h2 class="comments_header">Comments</h2>
          <% if @store.comments %>
            <% @store.comments.each do |comment| %>
          <!-- Display Actual Comment -->

            <div class="comment-content">
              <p><%= comment.content %></p>
            <% if comment.user == current_user %>
            <%= link_to "Delete Comment",  store_comment_path(@store, comment), method: :delete, data: { confirm: "Are you sure?" } %>
          </div><br>
      </div>
      <% end %>
  </div>
  <!-- Add Comment Form Ends -->

<% end %>
<% end %>
<% end %>

app/views/welcome/index.html.erb
<%= videojs_rails sources: { mp4: "https://s3.amazonaws.com/popstarvideos/ShopkeepingVideo.mp4"}, controls: false, autoplay: true, preload: 'auto',  width: '980' %>


<div id="polina">
  <h1>Popstar</h1>
  <a >Follow Us On Twitter</a>
  <br>
      <h4>Create and find popup stores in the coolest locations.</h4>
      <h4>We connect brands and boutiques with retail properties available for short terms.</h4>
      <%= link_to "Open a Popup", new_store_path, :class => "front_page_button" %>
      <%= link_to "Find a Popup", stores_path, :class => "front_page_button" %>

</div>

app/views/welcome/search.html.erb
<div class="mini_container">
<% @stores.each do |store| %> <div class="index_div">
  <div class="crop"><%= link_to image_tag(store.image.url(:medium),width: '100%', height: '100%', alt: 'Real Estate Image', class: "img-responsive"), store_path(store) %>  <h3 class="inside_text"> <span class="inside_span"> <%= store.caption %></span> </h3>
</div>
</div>
<div>

<% end %>